name: Update, Build, and Push Chocolatey Packages on Repository Dispatch

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package
        required: true 
        default: azure-kubelogin
        type: choice
        options:
          - azure-kubelogin
  repository_dispatch:
    types: [new-release]

jobs:
  update-build-push:
    runs-on: windows-latest
    env:
      PACKAGE: ${{ inputs.pacakge || github.event.client_payload.package }}
    defaults:
      run:
        shell: pwsh
        working-directory: ./${{ env.PACKAGE }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PowerShell Modules
      run: |
        Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
        Install-Module AU
        Install-Module GetRedirectedURL

    - name: Run update.ps1 for ${{ env.PACKAGE }}
      run: ./update.ps1

    - name: Commit & push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "Update ${{ env.PACKAGE }}"

    - name: Build ${{ env.PACKAGE }}
      id: build
      run: |
        $output = (choco pack)[2]
        "nupkg=$output" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
    
    - name: Extract nupkg filename
      id: filename
      run: |
        "${{ steps.build.outputs.nupkg }}" -match "([a-z0-9\-\.]+.nupkg)'$"
        $filename = $Matches[1]
        "nupkg=$filename" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: Push ${{ env.PACKAGE }} to Chocolatey
      env:
        CHOCO_API_KEY: ${{ secrets.ChocoApiKey }}
      run: |
        choco push ${{ steps.filename.outputs.nupkg }} --source https://push.chocolatey.org/ --api-key "$env:CHOCO_API_KEY"
