name: Update, Build, and Push Chocolatey Packages on Repository Dispatch

on: workflow_dispatch
    # inputs:
    #   package: 'Azure/kubelogin'
    #   version: '0.1.4'
  # repository_dispatch:
  #   types: [new-release]

jobs:
  update-build-push:
    # if: ${{ github.event.client_payload.package == 'Azure/kubelogin' || inputs.package == 'Azure/kubelogin' }}
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ./azure-kubelogin
    outputs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PowerShell Modules
      run: |
        Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
        Install-Module AU
        Install-Module GetRedirectedURL

    - name: Run update.ps1
      run: ./update.ps1

    - name: Build Chocolatey Package
      id: build
      run: |
        $output = choco pack
        Write-Host "::set-output name=nupkg::$output[2]"
    
    - name: Extract nupkg filename
      id: filename
      run: |
        $matches ${{ steps.build.outputs.nupkg }} -match "([a-z0-9\-\.]+.nupkg)'$"
        Write-Host "::set-output name=nupkg::$Matches[1]"

    - name: Push Chocolatey Package
      env:
        CHOCO_API_KEY: ${{ secrets.ChocoApiKey }}
      run: |
        choco push ${{ steps.filename.outputs.nupkg }} --source https://push.chocolatey.org/ --api-key "$env:CHOCO_API_KEY"
